Iter5
poggerr/go_shortener pull request #15
Opened 2023-05-08 12:15 UTC by poggerr

2023-05-08 22:03 UTC, maxlyaptsev requested changes

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/app/shorten.go
> +	MainMap[string(b)] = oldUrl
а что если в мапе уже есть такое значение? Есть вероятность что мы его перезапишем другим и предыдущая короткая ссылка работать перестанет

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/app/shorten.go
> +var MainMap = make(map[string]string)
использовать глобальную переменную для мапы опасно. Любой код сможет изменить в нем значения, удалить или добавить новые. Возможность изменять данные должно быть исключительно ответственностью соответствующего пакета
Использование локальной переменной тоже не рекомендуется - так данные в ней будут изменяться неявно и не будут ограничены определенными функциями - любая функция пакета так же будет иметь доступ.

2023-05-08 22:03 UTC, maxlyaptsev commented on config/flags/flags.go
> +package flags
пакет называется flags, но конфигурация происходит не только по флагам

2023-05-08 22:03 UTC, maxlyaptsev commented on config/flags/flags.go
> +var mainFlags = flag.NewFlagSet("main", flag.ExitOnError)
использование подкоманд тут лишнее флаги добавляются на основуню команду запуска приложения

2023-05-08 22:03 UTC, maxlyaptsev commented on config/flags/flags.go
> +	if string(DefUrl[len(DefUrl)-1]) != "/" {
мутировать флаг, заданный пользователем неправильно, лучше подставлять / при формировании ссылки

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/app/shorten.go
> +	return "Такого ключа нет"
правильней возвращать ошибку или boolean вторым аругментом

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/app/shorten_test.go
> +			ans := UnShorting(newUrl)
unit тесты должны быть независимые и проверять только одну функцию

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +	if req.Method != http.MethodGet {
роутер chi умеет различать get/post и другие методы, поэтому проверку делать не нужно

2023-05-08 22:03 UTC, maxlyaptsev commented on config/flags/flags.go
> +var Serv string
использовать глобальные переменные опасно - их можно изменить в любой части кода, а конфигурация приложения должна быть иммутабельна

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +		res.Write([]byte(err.Error()))
возвращать "голую" ошибку опасно - этими знаниями можно воспользоваться. Лучше залогировать ошибку для себя, но клиенту отдать что-то контролируемое и понятное ему

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +package handlers
здесь бы не помешали тесты, чтобы проверить что отдается верный статус и данные

2023-05-08 22:03 UTC, maxlyaptsev commented on internal/app/shorten.go
> +func Shorting(oldUrl string) string {
у пакета получается несколько ответсвенностей - он отвечает и за хранение данных и за логику создания коротких ссылок. Лучше разнести на два пакета

2023-05-13 19:30 UTC, maxlyaptsev requested changes

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +func SaveToMap(newUrl string, oldUrl string) string {
клиенту не важно куда сохраняется сущность, Save или Add достаточно

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +func GetFromMap(newUrl string) string {
Гетеры и сетеры в go не используются, для получения просто пишется имя того, что хотим получить

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/config/config.go
> +func GetServ() string {
если конфиг сделать стурктурой, не придется возвращать каждое поле отдельно

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/config/config.go
> +var serv string
не стоит использовать глобальные переменные, их можно легко изменить и сломать работу программы, это добавляет связанности - не понятно какая часть кода использует эти переменные и усложняет тестирование - в тесте тоже нужно как-то заполнить эти переменные

Как лучше - использовать структуру и конструктор

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func PostPage(res http.ResponseWriter, req *http.Request) {
это слой приложения и он не связан с http протоколом, поэтому Post использовать не совсем корректно. Лучше использовать функциональные названия, например  Create

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/handlers/handlers.go
> +func GetPage(res http.ResponseWriter, req *http.Request) {
Page неправильное название сущности, у нас приложение по сокращению ссылок и читая название метода не понятно что он делает

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/config/config.go
> +	if servRunAddr := os.Getenv("SERVER_ADDRESS"); servRunAddr != "" {
если использвоать сторонний пакет, установку значений из переменных окружения можно сократить до одной строки. Это значительно упростит читаемость, облегчит добавление новых переменных в конфиг и снизит вероятность ошибки

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/config/config.go
> +		defUrl += "/"
конфигурация заданная пользователем не должна неявно мутироваться, это усложнит дебаг кода. Другой разработчик будет пытаться понять откуда на конце появился слеш, когда в переменных окружения он его не указывал. После чего придется перелопатить почти весь код.

2023-05-13 19:30 UTC, maxlyaptsev commented on internal/routers/routers.go
> +func Routers() chi.Router {
```suggestion
func Router() chi.Router {
```

2023-05-16 16:38 UTC, maxlyaptsev requested changes

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/app.go
> +	if local != "" {
в конфиге у нас задается дефолтное значение, поэтому проверка лишняя

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/app.go
> +	res.Write([]byte(local))
Можно короче все записать:
```go
fmt.Fprint(res, a.cfg.DefUrl(), "/", short)
```

(уберем мутацию данных local += short, уберем local += "/" которое создает новый слайс и алоцирует новую память под новую строку и в целом сократим код)

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +	for key, value := range strg {
данные можно достать без перебора всех значений в мапе (это очень дорого, если записей сотни или тысячи)

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +	if strg == nil {
такой ситуации быть не может, мы вызываем метод структуры, она не может не существовать

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +func (strg Storage) Save(newUrl string, oldUrl string) string {
Стораджу не важно что с точки зрения бизнес логики мы сюда складываем. Возможно захочется использовать этот пакет в другом месте кода и хранить что-то совершенно другое
```suggestion
func (strg Storage) Save(key, value string) string {
```

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +func (strg Storage) Save(newUrl string, oldUrl string) string {
ресивер лучше делать по ссылке, если не нужно по каким-то причинам создавать копию структуры
```suggestion
func (s *Storage) Save(newUrl string, oldUrl string) string {
```

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +	return newUrl
нужно ли возвращать значение, которое метод сам же и получил? На это будет выделяться память, а коллеги будут искать причину - изменилось ли как-то значение.

2023-05-16 16:38 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +
```suggestion
```

2023-05-16 16:41 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +	return newUrl
Обычно возвращают ошибку, или nil если все прошло успешно

2023-05-16 17:01 UTC, poggerr commented on internal/app/storage/storage.go
> +	for key, value := range strg {
я просто не знаю как по значению получить ключ в golang

2023-05-16 17:01 UTC, poggerr commented on internal/app/storage/storage.go
> +	for key, value := range strg {
иным способом

2023-05-17 12:28 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +	(*strg)[key] = value
Чтобы таких вот корявостей не делать - лучше создать структуру с полем, в котором будут хранится данные. Хорошо бы поправить. 
```go
type Storage struct {
   data map[string]string
}

func NewStorage() *Storage {
	return &Storage{data: make(map[string]string)} // создаем стурктуру и возвращаем ссылку на нее
}
func (s *Storage) Add(key, value string) {s.data[key] = value}
func (s *Storage) Get(key, value string) { /* ... */ } // *Storage означает что мы работаем с ссылок а не с копией
```

2023-05-17 12:28 UTC, maxlyaptsev commented on internal/app/storage/storage.go
> +func (strg Storage) OldUrl(key string) (string, error) {
Не копируем, а берем ссылку на текущий сторадж
```suggestion
func (s *Storage) OldUrl(key string) (string, error) {
```

2023-06-06 11:01 UTC, merged