Iter18
poggerr/go_shortener pull request #37
Opened 2023-08-21 16:51 UTC by poggerr

2023-08-23 04:53 UTC, arttet requested changes

2023-08-23 04:53 UTC, arttet commented on cmd/shortener/.env
> +SECRET_KEY=scdcsdc,HVJHVCAJscdJccdsJVDVJDvqwe[p[;cqsc09cah989h
It should be in `gitignore`

2023-08-23 04:53 UTC, arttet commented on cmd/shortener/main.go
> +	"log"
Please sort imports

2023-08-23 04:53 UTC, arttet commented on cmd/shortener/main.go
> +		log.Print("No .env file found")
Please rewrite this part

2023-08-23 04:53 UTC, arttet commented on golangci.yaml
> +  disable-all: true
Please invert this value.

2023-08-23 04:53 UTC, arttet commented on internal/profiles/profile.pb
Why the extension is `.pb`?

2023-09-14 09:35 UTC, rktkov approved these changes

2023-09-14 09:35 UTC, rktkov commented on cmd/shortener/main.go
> +	"github.com/poggerr/go_shortener/internal/app/service"
Импорты все так же не отсортированы. (на каком языке предпочтительнее получать комментарии? русский или английский? )

2023-09-14 09:35 UTC, rktkov commented on cmd/shortener/main.go
> +		go repo.WorkerDeleteURLs()
А почему в горутину не передается контекст, который потом может быть использован для ее завершения во время завершения всего приложения? В такой ситуации можно напороться на "протекания горутин".

2023-09-14 16:43 UTC, poggerr commented on cmd/shortener/main.go
> +	"github.com/poggerr/go_shortener/internal/app/service"
Пиши на русском, чтобы не нарушать прежние комменты)

2023-10-09 10:18 UTC, rktkov approved these changes
Комментарии стоит поправить к следующему ПР.

2023-10-09 10:18 UTC, rktkov commented on internal/storage/save_to_file.go
> +		logger.Log.Error("Ошибка при сохранении файла ", err)
Похоже, что смешались 2 способа использования логгера. Стоит выбрать один и его использовать во всем коде. До этого  я видел logger.Initialize().Error...

2023-10-09 10:18 UTC, rktkov commented on internal/storage/get_urls_by_user.go
> +	"github.com/google/uuid"
Внешние и внутренние пакеты, тоже  стоит разделять при импорте.

2023-10-09 10:18 UTC, rktkov commented on internal/server/server.go
> +		//IdleTimeout:       120 * time.Second,
Если код не используется, его лучше удалять, а не комментировать.

2023-10-09 10:18 UTC, rktkov commented on internal/routers/routers_test.go
> +	"github.com/poggerr/go_shortener/internal/async"
Импорты перемешаны.

2023-10-09 10:18 UTC, rktkov commented on internal/app/create_json_shorten.go
> +	"encoding/json"
Импорты перемешаны. Следует везде в коде это поправить.

2023-10-10 11:14 UTC, merged